# set paths for imge folder ( 2 folders corresponding images have to have the same name)
#---------------------------------------------------------------------------------------
# Training set_up
#---------------------------------------------------------------------------------------
# input
train_dir : 'C:/Users/phili/OneDrive/Uni/WS_22/Masterarbeit/Masterarbeit_Code_Philipp_Rosin/Data_set_BCI_challange/train'
img_size : [64,64]
num_epochs : 1
decay_epoch : 1
batch_size : 1
norm : True
grayscale : False

# output save dirs
output_path : 'C:/Users/phili/OneDrive/Uni/WS_22/Masterarbeit/Masterarbeit_Code_Philipp_Rosin/torch_stain_transfer/experiment-results'
output_folder : 'Test_01'
model_name : 'Generator_G_weights.pth'

#-----------------------------------------------------------------------------------------
# Model selection
#-----------------------------------------------------------------------------------------
#set Generator architecture
conv_net : 1
trans_net: 0

# set CycleGAN LR and optimisers
learn_rate_disc : 0.0002
learn_rate_gen : 0.0002

beta1 : 0.5    #beta1 for Adam optimizer
beta2 : 0.999  #beta2 for Adam optimizer

# set CycleGAN loss hyperparameter
cycle_lambda : 4
identity_lambda : 2
generator_lambda : 1
disc_lambda : 1
ssim_lambda : 3
psnr_lambda : 0.05

# set conv architecture
num_gen_filters : 32   #number of generator filters
num_disc_filters : 64
num_resnet : 6 #number of resnet blocks

# set transformer architecture
nhead : 4
patch_size : 16
num_layers : 4
dropout_embedding : 0.1    


#-----------------------------------------------------------------------------------------
# Testing
#-----------------------------------------------------------------------------------------
test_dir : 'C:/Users/phili/OneDrive/Uni/WS_22/Masterarbeit/Masterarbeit_Code_Philipp_Rosin/Data_set_BCI_challange/val'
plots_per_epoch : 2










