# set paths for imge folder ( 2 folders corresponding images have to have the same name)
#------------------------------------------------------------------------------------------
# Training set_up
#------------------------------------------------------------------------------------------
# input
train_dir : 'C:/Users/phili/OneDrive/Uni/WS_22/Masterarbeit/Masterarbeit_Code_Philipp_Rosin/Data_set_BCI_challange/train'
img_size : [256,256]
in_channels : 3
num_epochs : 5
decay_epoch : 5
batch_size : 1
# put "normalise" and " grayscale"
preprocess_HE : ["normalise","colorjitter"]
preprocess_IHC : ["normalise","colorjitter"]

# output save dirs
output_path : 'C:/Users/phili/OneDrive/Uni/WS_22/Masterarbeit/Masterarbeit_Code_Philipp_Rosin/torch_stain_transfer/experiment-results'
output_folder : 'Test_03'
model_name : 'gen_G_weights_final.pth'

#---------------------------------------------------------------------------------------------
# Model selection
#---------------------------------------------------------------------------------------------
# set Generator architecture:
# options are: 'trans' or 'conv'
gen_architecture : 'trans'

# set CycleGAN LR and optimisers
learn_rate_disc : 0.0002
learn_rate_gen : 0.0002

# the beta1 and beta2 for the Adam optimizer used for both the total generator optimizer and total disc optimizer 
beta1 : 0.5   
beta2 : 0.999  

# set CycleGAN loss hyperparameter
cycle_lambda : 4
identity_lambda : .4
generator_lambda : 2
disc_lambda : 1
ssim_lambda : 3
psnr_lambda : 0.05


# ---------------------------- 'CONV' ARCHITECTURE ---------------------------------------------
num_gen_filters : 32   # num generator filters 
num_resnet : 9         # num of resnet blocks in the generator
num_disc_filters : 64  # num discriminator filters 
U_net_filter_groth : 2
U_net_step_num : 2


# ---------------------------- 'TRANS' ARCHITECTURE --------------------------------------------
nhead : 4
patch_size : 32
num_layers : 4
dropout_embedding : 0.1    


#-----------------------------------------------------------------------------------------------
# Testing
#-----------------------------------------------------------------------------------------------
test_dir : 'C:/Users/phili/OneDrive/Uni/WS_22/Masterarbeit/Masterarbeit_Code_Philipp_Rosin/Data_set_BCI_challange/val'
num_test_epochs: 2
plots_per_epoch : 2










