# set paths for imge folder ( 2 folders corresponding images have to have the same name)
#------------------------------------------------------------------------------------------
# Training set_up
#------------------------------------------------------------------------------------------
# input
train_dir : 'C:/Users/phili/OneDrive/Uni/WS_22/Masterarbeit/Masterarbeit_Code_Philipp_Rosin/Data_set_BCI_challange/train'
img_size : [256,256]
in_channels : 3
num_epochs : 5
decay_epoch : 5
batch_size : 1
# the preprocess list will determin the preprocesscing for each image HE/IHC before it will enter the network in tzraining 
#
# [normalise] -----> normalize the image based on the mean and std 
# either use the costum Mean and std of the bci train set for immunohistochemical dataset or the img_net mean and std
# use normalise_token for iether 'img_net' or 'bci'
normalise_token : 'bci'
mean_HE : [0.6374934061876859, 0.54221270388668, 0.6263932794073621]
std_HE : [0.08630574808474256, 0.09923751557584395, 0.07704577263561006]

mean_IHC : [0.7687480146058773, 0.7460195554334789, 0.7200858060498716]
std_IHC : [0.05067490897275364, 0.05804296102376095, 0.06596264508250156]

mean_img_net : [0.485, 0.456, 0.406] 
std_img_net: [0.229, 0.224, 0.225]

# [grayscale] --------------> transform the image into grayscale 
# [instance_norm] ----------> ?????????????
preprocess_HE : ['normalise']
preprocess_IHC : ['normalise']

# output save dirs
output_path : 'C:/Users/phili/OneDrive/Uni/WS_22/Masterarbeit/Masterarbeit_Code_Philipp_Rosin/torch_stain_transfer/experiment-results'
output_folder : 'Test_02'
model_name : 'gen_G_weights_final.pth'

#----------------------------------------------------------------------------------------------
# Model selection
#----------------------------------------------------------------------------------------------
# set Generator architecture and Discriminator architecture
# options are: 'trans' or 'conv'
gen_architecture : 'trans'
disc_architecture: 'trans'
# set frame architecture 
# otions are: 'cycleGan' or 'Gan'
frame_architecture: 'Gan'

# --------------------- Optemizer settings -----------------------------------------------------
# learningrate
learn_rate_disc : 0.0002
learn_rate_gen : 0.0002

# the beta1 and beta2 for the Adam optimizer used for both the total generator optimizer and total disc optimizer 
beta1 : 0.5   
beta2 : 0.999  

# --------------------- hyperparameter for [ Discriminator | Generator | SSIM | PSNR ] ----------
# set CycleGAN loss hyperparameter
generator_lambda : 1
disc_lambda : 1
ssim_lambda : 3
psnr_lambda : 0.05

# --------------------- hyperparameter for Cycle_Gan -------------------------------------------
cycle_lambda : 4
identity_lambda : .4

# -------------------- Total Gen Loss Composition ----------------------------------------------
# availeble inputs :
#   'gan_loss'  --------> vanilla GAN loss from goodfellow
#   'wgan_loss_gp' -----> wasserstein GAN loss with gradient penelty -----> set disc_iterations
#   'wgan_loss'---------> wasserstein loss weight clipping -----> set disc_iterations and weight clipping 
#   'ssim' -------------> SSIM loss (1-ssim(fake,real))
#   'psnr' -------------> PSNR loss
#   'MSE_loss' ---------> MSE between valid and disc output 

total_loss_comp : ['gan_loss']
disc_iterations : 4
weight_clipping : 0.01 
# ---------------------------- 'CONV' ARCHITECTURE ---------------------------------------------
num_gen_filters : 32   # num generator filters 
U_net_filter_groth : 2 # U net filter groth
U_net_step_num : 2
num_resnet : 9  


disc_filter_groth : 4
hidden_dim : 16
disc_step_num : 4


# ---------------------------- 'TRANS' ARCHITECTURE --------------------------------------------
num_heads_gen : 4
patch_size_gen : [16,16]
num_blocks_gen : 4   

num_heads_disc : 4
patch_size_disc : [16,16]
num_blocks_disc : 4 


#-----------------------------------------------------------------------------------------------
# Testing
#-----------------------------------------------------------------------------------------------
test_dir : 'C:/Users/phili/OneDrive/Uni/WS_22/Masterarbeit/Masterarbeit_Code_Philipp_Rosin/Data_set_BCI_challange/val'
num_test_epochs: 2
plots_per_epoch : 2










