batch_size: 1
beta1: 0.5
beta2: 0.999
conv_net: 1
cycle_lambda: 10
decay_epoch: 1
disc_lambda: 1
dropout_embedding: 0.1
generator_lambda: 1
identity_lambda: 5
img_size:
- 64
- 64
in_channels: 3
learn_rate_disc: 0.0002
learn_rate_gen: 0.0002
nhead: 4
num_disc_filters: 64
num_epochs: 1
num_gen_filters: 32
num_layers: 4
num_resnet: 6
output_folder: /Test_01
output_path: C:/Users/phili/OneDrive/Uni/WS_22/Masterarbeit/Masterarbeit_Code_Philipp_Rosin/torch_stain_transfer/experiment-results
patch_size: 16
test_dir: C:/Users/phili/OneDrive/Uni/WS_22/Masterarbeit/Masterarbeit_Code_Philipp_Rosin/Data_set_BCI_challange/val
train_dir: C:/Users/phili/OneDrive/Uni/WS_22/Masterarbeit/Masterarbeit_Code_Philipp_Rosin/Data_set_BCI_challange/train
trans_net: 0
